### ISSUE TITLE
ML consideration?

### ISSUE THREAD

**Issue by cloakedninjas** [unicef/projectconnect-app#10]
Hi - this project was sent around my work Slack and so I was taking a look at it when it struck me that the task being asked of users seems like it would be quite well suited to a ML algorithm.

Is this something you've already considered?

I'm no ML engineer myself, but perhaps the time spent in developing user management systems and adding sufficient gamification / incentivization could be spent on training an AI to recognise the patterns you're looking for

**Comment by lacabra** [comment]
Thanks @cloakedninjas for your suggestion. You are right that this might seem a tedious task to do manually and our vision is to automate the process as much as possible. For this, as you suggested, we are building ML that can automatically map schools from satellite imagery. We first did this for Colombia (http://devseed.com/unicef-school-docs/) and we are now adapting the models to different regions and contexts. However, you need considerable large amounts of quality training data to feed the models and we are therefore planning to use data tagged and validated through the crowdsourcing game as one of the inputs to train our ML models. In addition, the ML predictions are not 100% accurate and it involves a 'human-in-the-loop' type of process. We are therefore again envisioning that the crowdsourcing game will help us validate the predictions made by the ML models (and that would again be inputted back into the model).
